### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by tomicakorac** [yasharrashedi/LimitlessLED#12]
I'd like to know what's the current status of this project. s it still being developed? Will it work with the actual Milight hardware?

**Comment by yasharrashedi** [comment]
this project has not been developed since wifi bridge v.4 but should work with v.5 / v.6. I don't have the latest hardware to test software on

**Comment by tomicakorac** [comment]
@yasharrashedi thanks a lot for your answer.

**Comment by tomicakorac** [comment]
@yasharrashedi thanks a lot for your answer.
