### ISSUE TITLE
Firmware for v4

### ISSUE THREAD

**Issue by mrwhale** [yasharrashedi/LimitlessLED#7]
Not a bug, but just wondering if you still have a copy of the firmware for the update? I would like to update my bridge to the latest version (cant find it anywhere else!)

Thanks :)

**Comment by yasharrashedi** [comment]
Yes I have, please drop me an email I'll send you the file back. but be informed that some people broke their devices by updating the firmware, DO IT AT YOUR OWN RISK!
my email info@rashedi.com

**Comment by macmonty** [comment]
Hello have you de firmware update for de V4, i dont find anymore.
Thanks a lot
